apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    environment: development
  annotations:
    description: This is a replica set
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx
      - key: env
        operator: In
        values:
          - dev
          - qa
          - prod
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
